# Generated by Django 3.2.13 on 2022-07-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paymented',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.CharField(blank=True, max_length=30)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
